#
# Some constants
#
API_SIGN <- writeBin("API", raw()) # "API\0" (the null termination is added automatically by writeBin()

HEADER_LEN  <- 4L
MAX_MSG_LEN <- 0xFFFFFFL  # 16Mb - 1b

# Server Versions
MIN_SERVER_VER_SCANNER_GENERIC_OPTS    <- 143L
MIN_SERVER_VER_API_BIND_ORDER          <- 144L
MIN_SERVER_VER_ORDER_CONTAINER         <- 145L
MIN_SERVER_VER_SMART_DEPTH             <- 146L
MIN_SERVER_VER_REMOVE_NULL_ALL_CASTING <- 147L
MIN_SERVER_VER_D_PEG_ORDERS            <- 148L
MIN_SERVER_VER_MKT_DEPTH_PRIM_EXCHANGE <- 149L
MIN_SERVER_VER_COMPLETED_ORDERS        <- 150L
MIN_SERVER_VER_PRICE_MGMT_ALGO         <- 151L
MIN_SERVER_VER_STOCK_TYPE              <- 152L
MIN_SERVER_VER_ENCODE_MSG_ASCII7       <- 153L
MIN_SERVER_VER_SEND_ALL_FAMILY_CODES   <- 154L
MIN_SERVER_VER_NO_DEFAULT_OPEN_CLOSE   <- 155L
MIN_SERVER_VER_PRICE_BASED_VOLATILITY  <- 156L
MIN_SERVER_VER_REPLACE_FA_END          <- 157L

MIN_CLIENT_VER <- 142L
MAX_CLIENT_VER <- MIN_SERVER_VER_REPLACE_FA_END
