#
# Some constants
#
API_SIGN <- writeBin("API", raw()) # "API\0" (the null termination is added automatically by writeBin()

HEADER_LEN  <- 4L
MAX_MSG_LEN <- 0xFFFFFFL  # 16Mb - 1b

RAWID_LEN <- 4L
PROTOBUF_MSG_ID <- 200L

# Server Versions
MIN_SERVER_VER_ADD_Z_SUFFIX_TO_UTC_DATE_TIME    <- 214L
MIN_SERVER_VER_CANCEL_CONTRACT_DATA             <- 215L
MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_1        <- 216L
MIN_SERVER_VER_ADDITIONAL_ORDER_PARAMS_2        <- 217L
MIN_SERVER_VER_ATTACHED_ORDERS                  <- 218L
MIN_SERVER_VER_CONFIG                           <- 219L


MIN_CLIENT_VER <- 213L
MAX_CLIENT_VER <- MIN_SERVER_VER_CONFIG
